apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    k8s-app: url-shortener
    kubernetes.io/name: url-shortener    
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: url-shortener
  template:
    metadata:
      labels:
        k8s-app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: pw/crudservice:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - mountPath: /app/service.cfg
          subPath: service.cfg
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          name: url-shortener
        name: config-volume